from typing import Any
from weasyprint import HTML
from jinja2 import Template

PDF_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 40px;
        }
        h1 {
            color: #1a1a1a;
            border-bottom: 2px solid #e5e5e5;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        h2 {
            color: #444;
            margin-top: 30px;
            margin-bottom: 15px;
        }
        .header {
            margin-bottom: 30px;
        }
        .meta {
            color: #666;
            font-size: 14px;
            margin-bottom: 20px;
        }
        .recommendation {
            display: inline-block;
            padding: 8px 16px;
            border-radius: 4px;
            font-weight: bold;
            font-size: 14px;
            text-transform: uppercase;
            margin-bottom: 20px;
        }
        .recommendation.ship {
            background-color: #d4edda;
            color: #155724;
        }
        .recommendation.needs_work {
            background-color: #fff3cd;
            color: #856404;
        }
        .recommendation.block {
            background-color: #f8d7da;
            color: #721c24;
        }
        .summary {
            background-color: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 30px;
        }
        .findings {
            margin-bottom: 30px;
        }
        .findings ul {
            padding-left: 20px;
        }
        .findings li {
            margin-bottom: 10px;
        }
        .metrics-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
        }
        .metrics-table th,
        .metrics-table td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }
        .metrics-table th {
            background-color: #f8f9fa;
            font-weight: 600;
        }
        .section {
            margin-bottom: 25px;
        }
        .section-content {
            color: #555;
        }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e5e5e5;
            font-size: 12px;
            color: #888;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ project_name }}</h1>
        <div class="meta">
            <strong>Run:</strong> {{ run_name }}<br>
            <strong>Generated:</strong> {{ generated_at }}
        </div>
        {% if recommendation %}
        <div class="recommendation {{ recommendation }}">
            {% if recommendation == 'ship' %}Ready to Ship{% endif %}
            {% if recommendation == 'needs_work' %}Needs Work{% endif %}
            {% if recommendation == 'block' %}Blocked{% endif %}
        </div>
        {% endif %}
    </div>

    <h2>Executive Summary</h2>
    <div class="summary">
        {{ summary | replace('\\n', '<br>') | safe }}
    </div>

    {% if key_findings %}
    <div class="findings">
        <h2>Key Findings</h2>
        <ul>
            {% for finding in key_findings %}
            <li>{{ finding }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}

    {% if metrics %}
    <h2>Metrics</h2>
    <table class="metrics-table">
        <tr>
            <th>Metric</th>
            <th>Value</th>
        </tr>
        {% for key, value in metrics.items() %}
        <tr>
            <td>{{ key | replace('_', ' ') | title }}</td>
            <td>{{ value }}</td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}

    {% if risk_assessment %}
    <div class="section">
        <h2>Risk Assessment</h2>
        <div class="section-content">
            {{ risk_assessment | replace('\\n', '<br>') | safe }}
        </div>
    </div>
    {% endif %}

    {% if trade_offs %}
    <div class="section">
        <h2>Trade-offs</h2>
        <div class="section-content">
            {{ trade_offs | replace('\\n', '<br>') | safe }}
        </div>
    </div>
    {% endif %}

    <div class="footer">
        Generated by Eval Platform
    </div>
</body>
</html>
"""


def generate_pdf(report_data: dict[str, Any]) -> bytes:
    template = Template(PDF_TEMPLATE)
    html_content = template.render(**report_data)
    pdf = HTML(string=html_content).write_pdf()
    return pdf
