import { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { ReportView } from '../components/ReportView';
import { getPublicReport } from '../api/client';
import type { Report } from '../types/eval';

export function PublicReport() {
  const { token } = useParams<{ token: string }>();
  const [report, setReport] = useState<Report | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (token) {
      loadReport();
    }
  }, [token]);

  const loadReport = async () => {
    try {
      setLoading(true);
      const data = await getPublicReport(token!);
      setReport(data);
    } catch (err) {
      setError('Report not found or link has expired');
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto"></div>
          <p className="text-gray-600 mt-2">Loading report...</p>
        </div>
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <svg className="mx-auto h-12 w-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.172 16.172a4 4 0 015.656 0M9 10h.01M15 10h.01M12 2C6.477 2 2 6.477 2 12s4.477 10 10 10 10-4.477 10-10S17.523 2 12 2z" />
          </svg>
          <h2 className="mt-2 text-lg font-medium text-gray-900">Report Not Found</h2>
          <p className="mt-1 text-gray-500">{error || 'This report does not exist or has been removed.'}</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-4xl mx-auto px-4 py-8">
        <div className="mb-6 text-center">
          <p className="text-sm text-gray-500">Shared Report</p>
        </div>
        <ReportView report={report} showActions={false} />
        <div className="mt-8 text-center text-sm text-gray-500">
          Generated by Eval Platform
        </div>
      </div>
    </div>
  );
}
